name: Deploy Pages

on:
  push:
    branches: [ main,digitalTube ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node main
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Setup Pages main
        uses: actions/configure-pages@v4
      - name: Install dependencies main
        run: pnpm install
      - name: Build main
        run: pnpm run build
      - name: Upload artifact main
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: dist

  build-digitalTube:
    needs: build-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout digitalTube
        uses: actions/checkout@v4
        with:
          ref: digitalTube
      - name: Setup Node digitalTube
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Setup Pages digitalTube
        uses: actions/configure-pages@v4
      - name: Install dependencies digitalTube
        run: npm install
      - name: Build digitalTube
        run: npm run build
      - name: Move files to digitalTube
        run: |
          mkdir -p dist/digitalTube
          cd dist
          mv `ls|grep -v "digitalTube"` digitalTube
      - name: Upload artifact digitalTube
        uses: actions/upload-artifact@v3
        with:
          name: digitalTube
          path: dist/digitalTube

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [ build-main, build-digitalTube ]
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: main
          path: dist
      - uses: actions/download-artifact@v3
        with:
          name: digitalTube
          path: dist/digitalTube
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4